export const SET_STREETS = 'SET_STREETS';
export const SET_HOUSES = 'SET_HOUSES';
export const SET_FLATS = 'SET_FLATS';
export const SET_SELECTED_FLAT = 'SET_SELECTED_FLAT';
export const SET_SELECTED_STREET = 'SET_SELECTED_STREET';
export const SET_CLIENT_LIST = 'SET_CLIENT_LIST';
export const SET_SELECTED_HOUSE = 'SET_SELECTED_HOUSE';
